apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: redis
  name: redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: redis
  template:
    metadata:
      labels:
        run: redis
    spec:
      containers:
      - args:
        - /etc/redis/redis.conf
        image: redis
        name: redis
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /etc/redis/redis.conf
          name: config
      volumes:
      - gcePersistentDisk:
          fsType: ext4
          pdName: redis
        name: data
      - configMap:
          name: redis-v1
        name: config
