apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: registry
  name: registry
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      run: registry
  template:
    metadata:
      labels:
        run: registry
    spec:
      containers:
      - image: registry:2.5.1
        name: registry
        volumeMounts:
        - mountPath: /var/lib/registry
          name: data
      volumes:
      - gcePersistentDisk:
          pdName: registry
        name: data
