apiVersion: v1
kind: Service
metadata:
  labels:
    run: registry
  name: registry
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    nodePort: 30015
  selector:
    run: registry
